### ISSUE TITLE
Issue compileing no piimg.h

### ISSUE THREAD

**Issue by wendelit** [alexchamberlain/piimg#5]
When i try to run make in the src folder i get:
piimg.c:6:19: piimg.h file dose not exist

**Comment by alexchamberlain** [comment]
Have you run `make` in `lib`? Try running that first and then run `make` in `src`.

I know this isn't ideal... I'll sort it out with a top-level `Makefile` soon.

**Comment by wendelit** [comment]
There we go, Thanks!
